[build]
  publish = "public"
  functions = "public/netlify/functions"

[dev]
  publish = "public"
  functions = "public/netlify/functions"
  
[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"