name: Auto Generate Cards from Airtable

on:
  schedule:
    - cron: '0,30 * * * *'  # 每30分钟执行一次
  workflow_dispatch:     # 也支持手动点击运行

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Debug puppeteer
        run: |
          npm ls puppeteer
          npm ls puppeteer-core || echo "✅ puppeteer-core removed"

      - name: Install puppeteer Chromium
        run: npx puppeteer browsers install chrome

      - name: Run generate-from-airtable.js
        run: node scripts/generate-from-airtable.js

      - name: Commit and push with token
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          
          echo "🔐 设置远程地址为 token 模式"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
      
          echo "🧹 还原不需要提交的文件"
          git restore package-lock.json
      
          echo "📦 添加更改"
          git add docs/generated/inspiration-cards/
          git commit -m "🤖 更新 Airtable 卡片图和展示页" || echo "No changes to commit"
      
          echo "🚀 推送主分支"
          git push origin HEAD:main --force-with-lease

