name: Auto Generate Cards from Airtable

on:
  schedule:
    - cron: '0,30 * * * *'  # 每30分钟执行一次
  workflow_dispatch:     # 也支持手动点击运行

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Debug puppeteer
        run: |
          npm ls puppeteer
          npm ls puppeteer-core || echo "✅ puppeteer-core removed"

      - name: Install puppeteer Chromium
        run: npx puppeteer browsers install chrome

      - name: Run generate-from-airtable.js
        run: node scripts/generate-from-airtable.js

      - name: Push generated docs using GH_PAT (clean repo)
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          echo "📦 构建临时 Git 仓库用于推送 docs 内容"
          
          mkdir temp-push
          cd temp-push
          
          git init
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git remote add origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          
          git fetch origin main
          git checkout -b main origin/main
          
          # ⬇️ now copy doc/
          cp -r ../docs/* .
          
          git add .
          git commit -m "🤖 自动生成并推送 docs"
          git push origin main --force-with-lease
          
      - name: Show logs
        if: always()
        run: |
          echo "🎯 Workflow 执行完成"



