name: Auto Generate Cards from Airtable

on:
  schedule:
    - cron: '0,30 * * * *'  # 每30分钟执行一次
  workflow_dispatch:     # 也支持手动点击运行

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Debug puppeteer
        run: |
          npm ls puppeteer
          npm ls puppeteer-core || echo "✅ puppeteer-core removed"

      - name: Install puppeteer Chromium
        run: npx puppeteer browsers install chrome

      - name: Run generate-from-airtable.js
        run: node scripts/generate-from-airtable.js

      - name: Force override Git remote with token
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
      
          echo "🔧 手动覆盖 .git/config 以设置 Token Remote"
          git config --unset-all remote.origin.url || true
          git config --add remote.origin.url "https://x-access-token:${GH_PAT}@github.com/${GITHUB_REPOSITORY}"
      
          echo "🧪 验证 remote 设置："
          git remote -v
      
          git restore package-lock.json
          git add docs/generated/inspiration-cards/
          git commit -m "🤖 更新 Airtable 卡片图和展示页" || echo "⚠️ No changes to commit"
      
          echo "🚀 正在推送"
          git push origin HEAD:main --force-with-lease

